version: '3'

services:
    esp_idf:
        image: esp_idf
        tty: true # Prevent immediate exit when running with dev containers
        network_mode: "host"
        build:
            context: ..
            dockerfile: docker/esp_idf.Dockerfile
        privileged: true # Required to flash esp (sorry windows and mac folks)
        volumes:
            - ..:/esp32_firmware
            - /dev:/dev
