/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Joint {
    Joint_RIGHT_WHEEL = 0,
    Joint_LEFT_WHEEL = 1
} Joint;

/* Incoming */
typedef enum _IncomingMessageID {
    IncomingMessageID_JOINT_CMD = 0,
    IncomingMessageID_incoming_msg_count = 1
} IncomingMessageID;

/* Outgoing */
typedef enum _OutgoingMessageID {
    OutgoingMessageID_NONE = 0,
    OutgoingMessageID_JOINT_STATES_DATA = 1,
    OutgoingMessageID_IMU_DATA = 2,
    OutgoingMessageID_LIDAR_DATA = 3,
    OutgoingMessageID_BATTERY_DATA = 4,
    OutgoingMessageID_outgoing_msg_count = 5
} OutgoingMessageID;

/* Struct definitions */
/* Util */
typedef struct _TimeStamp {
    int32_t sec;
    uint32_t nanosec;
} TimeStamp;

typedef struct _SubscribeRequest {
    OutgoingMessageID msg_id;
} SubscribeRequest;

typedef struct _JointCmd {
    bool has_time;
    TimeStamp time;
    Joint joint;
    float vel;
} JointCmd;

typedef struct _IncomingCommand {
    bool has_subscribe_request;
    SubscribeRequest subscribe_request;
    bool has_joint_cmd;
    JointCmd joint_cmd;
} IncomingCommand;

typedef struct _LaserScan {
    bool has_time;
    TimeStamp time;
    float angle_min;
    float angle_max;
    float angle_increment;
    float time_increment;
    float scan_time;
    float range_min;
    float range_max;
    pb_size_t ranges_count;
    float ranges[12];
    pb_size_t intensities_count;
    float intensities[12];
} LaserScan;

typedef struct _JointState {
    Joint joint;
    bool has_time;
    TimeStamp time;
    double position;
    double velocity;
    double effort;
} JointState;

typedef struct _IMU {
    bool has_time;
    TimeStamp time;
    float gyro_x;
    float gyro_y;
    float gyro_z;
    float accel_x;
    float accel_y;
    float accel_z;
} IMU;

typedef struct _OutgoingData {
    OutgoingMessageID msg_id;
    pb_size_t laser_count;
    LaserScan laser[10];
    bool has_joint_state;
    JointState joint_state;
    bool has_imu;
    IMU imu;
} OutgoingData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Joint_MIN Joint_RIGHT_WHEEL
#define _Joint_MAX Joint_LEFT_WHEEL
#define _Joint_ARRAYSIZE ((Joint)(Joint_LEFT_WHEEL+1))

#define _IncomingMessageID_MIN IncomingMessageID_JOINT_CMD
#define _IncomingMessageID_MAX IncomingMessageID_incoming_msg_count
#define _IncomingMessageID_ARRAYSIZE ((IncomingMessageID)(IncomingMessageID_incoming_msg_count+1))

#define _OutgoingMessageID_MIN OutgoingMessageID_NONE
#define _OutgoingMessageID_MAX OutgoingMessageID_outgoing_msg_count
#define _OutgoingMessageID_ARRAYSIZE ((OutgoingMessageID)(OutgoingMessageID_outgoing_msg_count+1))


#define SubscribeRequest_msg_id_ENUMTYPE OutgoingMessageID

#define JointCmd_joint_ENUMTYPE Joint



#define JointState_joint_ENUMTYPE Joint


#define OutgoingData_msg_id_ENUMTYPE OutgoingMessageID


/* Initializer values for message structs */
#define TimeStamp_init_default                   {0, 0}
#define SubscribeRequest_init_default            {_OutgoingMessageID_MIN}
#define JointCmd_init_default                    {false, TimeStamp_init_default, _Joint_MIN, 0}
#define IncomingCommand_init_default             {false, SubscribeRequest_init_default, false, JointCmd_init_default}
#define LaserScan_init_default                   {false, TimeStamp_init_default, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define JointState_init_default                  {_Joint_MIN, false, TimeStamp_init_default, 0, 0, 0}
#define IMU_init_default                         {false, TimeStamp_init_default, 0, 0, 0, 0, 0, 0}
#define OutgoingData_init_default                {_OutgoingMessageID_MIN, 0, {LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default, LaserScan_init_default}, false, JointState_init_default, false, IMU_init_default}
#define TimeStamp_init_zero                      {0, 0}
#define SubscribeRequest_init_zero               {_OutgoingMessageID_MIN}
#define JointCmd_init_zero                       {false, TimeStamp_init_zero, _Joint_MIN, 0}
#define IncomingCommand_init_zero                {false, SubscribeRequest_init_zero, false, JointCmd_init_zero}
#define LaserScan_init_zero                      {false, TimeStamp_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define JointState_init_zero                     {_Joint_MIN, false, TimeStamp_init_zero, 0, 0, 0}
#define IMU_init_zero                            {false, TimeStamp_init_zero, 0, 0, 0, 0, 0, 0}
#define OutgoingData_init_zero                   {_OutgoingMessageID_MIN, 0, {LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero, LaserScan_init_zero}, false, JointState_init_zero, false, IMU_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define TimeStamp_sec_tag                        1
#define TimeStamp_nanosec_tag                    2
#define SubscribeRequest_msg_id_tag              1
#define JointCmd_time_tag                        1
#define JointCmd_joint_tag                       2
#define JointCmd_vel_tag                         3
#define IncomingCommand_subscribe_request_tag    1
#define IncomingCommand_joint_cmd_tag            2
#define LaserScan_time_tag                       1
#define LaserScan_angle_min_tag                  2
#define LaserScan_angle_max_tag                  3
#define LaserScan_angle_increment_tag            4
#define LaserScan_time_increment_tag             5
#define LaserScan_scan_time_tag                  6
#define LaserScan_range_min_tag                  7
#define LaserScan_range_max_tag                  8
#define LaserScan_ranges_tag                     9
#define LaserScan_intensities_tag                10
#define JointState_joint_tag                     1
#define JointState_time_tag                      2
#define JointState_position_tag                  3
#define JointState_velocity_tag                  4
#define JointState_effort_tag                    5
#define IMU_time_tag                             1
#define IMU_gyro_x_tag                           2
#define IMU_gyro_y_tag                           3
#define IMU_gyro_z_tag                           4
#define IMU_accel_x_tag                          5
#define IMU_accel_y_tag                          6
#define IMU_accel_z_tag                          7
#define OutgoingData_msg_id_tag                  1
#define OutgoingData_laser_tag                   2
#define OutgoingData_joint_state_tag             3
#define OutgoingData_imu_tag                     4

/* Struct field encoding specification for nanopb */
#define TimeStamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    sec,               1) \
X(a, STATIC,   SINGULAR, UINT32,   nanosec,           2)
#define TimeStamp_CALLBACK NULL
#define TimeStamp_DEFAULT NULL

#define SubscribeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    msg_id,            1)
#define SubscribeRequest_CALLBACK NULL
#define SubscribeRequest_DEFAULT NULL

#define JointCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              1) \
X(a, STATIC,   SINGULAR, UENUM,    joint,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    vel,               3)
#define JointCmd_CALLBACK NULL
#define JointCmd_DEFAULT NULL
#define JointCmd_time_MSGTYPE TimeStamp

#define IncomingCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  subscribe_request,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  joint_cmd,         2)
#define IncomingCommand_CALLBACK NULL
#define IncomingCommand_DEFAULT NULL
#define IncomingCommand_subscribe_request_MSGTYPE SubscribeRequest
#define IncomingCommand_joint_cmd_MSGTYPE JointCmd

#define LaserScan_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_min,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_max,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_increment,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    time_increment,    5) \
X(a, STATIC,   SINGULAR, FLOAT,    scan_time,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    range_min,         7) \
X(a, STATIC,   SINGULAR, FLOAT,    range_max,         8) \
X(a, STATIC,   REPEATED, FLOAT,    ranges,            9) \
X(a, STATIC,   REPEATED, FLOAT,    intensities,      10)
#define LaserScan_CALLBACK NULL
#define LaserScan_DEFAULT NULL
#define LaserScan_time_MSGTYPE TimeStamp

#define JointState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    joint,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              2) \
X(a, STATIC,   SINGULAR, DOUBLE,   position,          3) \
X(a, STATIC,   SINGULAR, DOUBLE,   velocity,          4) \
X(a, STATIC,   SINGULAR, DOUBLE,   effort,            5)
#define JointState_CALLBACK NULL
#define JointState_DEFAULT NULL
#define JointState_time_MSGTYPE TimeStamp

#define IMU_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,           7)
#define IMU_CALLBACK NULL
#define IMU_DEFAULT NULL
#define IMU_time_MSGTYPE TimeStamp

#define OutgoingData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    msg_id,            1) \
X(a, STATIC,   REPEATED, MESSAGE,  laser,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  joint_state,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu,               4)
#define OutgoingData_CALLBACK NULL
#define OutgoingData_DEFAULT NULL
#define OutgoingData_laser_MSGTYPE LaserScan
#define OutgoingData_joint_state_MSGTYPE JointState
#define OutgoingData_imu_MSGTYPE IMU

extern const pb_msgdesc_t TimeStamp_msg;
extern const pb_msgdesc_t SubscribeRequest_msg;
extern const pb_msgdesc_t JointCmd_msg;
extern const pb_msgdesc_t IncomingCommand_msg;
extern const pb_msgdesc_t LaserScan_msg;
extern const pb_msgdesc_t JointState_msg;
extern const pb_msgdesc_t IMU_msg;
extern const pb_msgdesc_t OutgoingData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TimeStamp_fields &TimeStamp_msg
#define SubscribeRequest_fields &SubscribeRequest_msg
#define JointCmd_fields &JointCmd_msg
#define IncomingCommand_fields &IncomingCommand_msg
#define LaserScan_fields &LaserScan_msg
#define JointState_fields &JointState_msg
#define IMU_fields &IMU_msg
#define OutgoingData_fields &OutgoingData_msg

/* Maximum encoded size of messages (where known) */
#define IMU_size                                 49
#define IncomingCommand_size                     32
#define JointCmd_size                            26
#define JointState_size                          48
#define LaserScan_size                           174
#define MESSAGES_PB_H_MAX_SIZE                   OutgoingData_size
#define OutgoingData_size                        1873
#define SubscribeRequest_size                    2
#define TimeStamp_size                           17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
