/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TimeStamp, TimeStamp, AUTO)


PB_BIND(SubscribeRequest, SubscribeRequest, AUTO)


PB_BIND(JointCmd, JointCmd, AUTO)


PB_BIND(IncomingCommand, IncomingCommand, AUTO)


PB_BIND(LaserScan, LaserScan, AUTO)


PB_BIND(JointState, JointState, AUTO)


PB_BIND(IMU, IMU, AUTO)


PB_BIND(OutgoingData, OutgoingData, 2)






